KABU_Blog/Blog.AI/Controllers/BlockerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.AI.Controllers
{
    public class BlockerController : Controller
    {
        // GET: Blocker
        public ActionResult Index()
        {
            return View();
        }
    }
}

KABU_Blog/Blog.AI/Controllers/CommonController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Blog.AI.Models;
using Blog.Models.Types;
using Blog.Mvc;
using Blog.Services;
using Microsoft.AspNet.Identity;

namespace Blog.AI.Controllers
{
    public class CommonController : KabuController
    {
        private IContactService _contactService;

        public CommonController(IContactService contactService)
        {
            this._contactService = contactService;
        }


        public ActionResult _Header()
        {
            return PartialView("_Header");
        }

        public ActionResult _Navigation()
        {
            dynamic navigation = new ExpandoObject();
            navigation.controller = GetRoute("controller", true);
            navigation.action = GetRoute("action", true);


            return PartialView("_Navigation", navigation);
        }

        public ActionResult _Notifications()
        {
            return PartialView("_Notifications");
        }

        public ActionResult _Contacts()
        {
            var orderedContacts = _contactService.Get().Result.Where(con => con.ContactStatus == ContactStatus.UnRead).OrderByDescending(con => con.Created);
            var contactViewModel = new ContactViewModel
            {
                Contacts = orderedContacts.Take(5).ToList(),
                TotalContact = orderedContacts.Count(),
                UnReadCount = orderedContacts.Count(con => con.ContactStatus == ContactStatus.UnRead && con.Status != Status.Deleted)
            };

            return PartialView("_Contacts", contactViewModel);
        }
    }
}

KABU_Blog/Blog.AI/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Blog.AI.Models;
using Blog.Models;
using Blog.Models.Types;
using Blog.Mvc;
using Blog.Services;

namespace Blog.AI.Controllers
{
    public class ContactController : KabuController
    {
        private IContactService _contactService;

        public ContactController(IContactService contactService)
        {
            _contactService = contactService;
        }

        // GET: Contact
        public ActionResult Index()
        {
            return View(GenerateTableModel(new TableViewModel<Contact>()));
        }

        [HttpPost]
        public JsonResult RefreshTableData(TableViewModel<Contact> tableModel)
        {
            var viewResult = RenderRazorViewToString("Table", GenerateTableModel(tableModel));

            return Json(new { view = viewResult, IsCompleted = true });
        }

        public async Task<ActionResult> ReadMessage(int id)
        {
            var contact = await _contactService.FindById(id);

            if (contact == null)
                return Index();

            return View(contact);
        }

        public async Task<JsonResult> Remove(int id)
        {
            var model = await _contactService.FindById(id);

            if (model == null)
                return Json(new { IsCompleted = false, title = "Hata !", message = "Model Bulunamadı !" }, JsonRequestBehavior.AllowGet);

            _contactService.Delete(model);

            return Json(new { IsCompleted = true, title = "Başarılı !", message = "Başarı ile silindi !" }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Update(int id, ContactStatus ContactStatus)
        {
            var updatingModel = await _contactService.FindById(id);

            if (updatingModel == null)
                throw new Exception("Model bulunamadı.");

            updatingModel.ContactStatus = ContactStatus;

            var viewResult = RenderRazorViewToString("Show", updatingModel);

            if (!ModelState.IsValid)
                return Json(new { view = viewResult, IsCompleted = false }, JsonRequestBehavior.AllowGet);

            _contactService.Update(updatingModel);

            return Json(new { view = viewResult, title = "Başarılı !", message = "Başarı ile güncellendi.", IsCompleted = true }, JsonRequestBehavior.AllowGet);
        }

        private TableViewModel<Contact> GenerateTableModel(TableViewModel<Contact> table)
        {
            var search = table.Search ?? "";

            var tableList =
                _contactService.Get(
                    x => x.Status != Status.Deleted && (
                        x.Email.Contains(search) || x.Fullname.Contains(search) || x.Message.Contains(search) ||
                        x.Title.Contains(search) || x.UserIp.Contains(search) || x.PhoneNumber.Contains(search))).Result;

            table.Hits = tableList.OrderByDescending(x => x.Id).Skip((table.CurrentPage - 1) * table.Perpage).Take(table.Perpage).ToList();
            table.TotalCount = tableList.Count();
            return table;
        }
    }
}

KABU_Blog/Blog.AI/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using Blog.AI.Models;
using Blog.Models;
using Blog.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace Blog.AI.Controllers
{
    public class ProfileController : KabuController
    {
        private ApplicationUserManager _userManager;

        public ProfileController()
        {

        }
        public ProfileController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }


        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        // GET: Profile
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Informations()
        {
            var currentUser = UserManager.FindByIdAsync(User.Identity.GetUserId()).Result;
            var userInformation = new UserInformationViewModel
            {
                Name = currentUser.Name,
                Birthdate = currentUser.Birthdate,
                Surname = currentUser.Surname
            };

            return PartialView(userInformation);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveInformations(UserInformationViewModel userInformation)
        {
            var viewResult = RenderRazorViewToString("Informations", userInformation);

            if (!ModelState.IsValid)
                return Json(new { view = viewResult, IsCompleted = false }, JsonRequestBehavior.AllowGet);

            var currentUser = UserManager.FindByIdAsync(User.Identity.GetUserId()).Result;
            currentUser.Name = userInformation.Name;
            currentUser.Surname = userInformation.Surname;
            currentUser.Birthdate = userInformation.Birthdate;

            var result = UserManager.Update(currentUser);

            return Json(result.Succeeded ? new { view = viewResult, title = "Başarılı !", message = "Kullanıcı bilgileri başarıyla kayıt edildi.", IsCompleted = true } : new { view = viewResult, title = "Hata !", message = GetErrorMessage(result.Errors), IsCompleted = false }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult ChangePassword()
        {
            return PartialView();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> SaveChangePassword(ChangePasswordViewModel changePassword)
        {
            var viewResult = RenderRazorViewToString("ChangePassword", changePassword);
            if (!ModelState.IsValid)
                return Json(new { view = viewResult, IsCompleted = false }, JsonRequestBehavior.AllowGet);

            var currentUser = UserManager.FindByIdAsync(User.Identity.GetUserId()).Result;
            var result = await UserManager.ChangePasswordAsync(currentUser.Id, changePassword.OldPassword, changePassword.NewPassword);

            return Json(result.Succeeded ? new { view = viewResult, title = "Başarılı !", message = "Şifre başarıyla değiştirildi.", IsCompleted = true } : new { view = viewResult, title = "Hata !", message = GetErrorMessage(result.Errors), IsCompleted = false }, JsonRequestBehavior.AllowGet);
        }


        public ActionResult _LoginPartial()
        {
            var currentUser = UserManager.FindByNameAsync(User.Identity.Name).Result;
            return PartialView("_LoginPartial", currentUser.Name + " " + currentUser.Surname);
        }

    }
}

KABU_Blog/Blog.AI/Controllers/SettingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Blog.AI.Models;
using Blog.Models;
using Blog.Models.Types;
using Blog.Mvc;
using Blog.Services;

namespace Blog.AI.Controllers
{
    public class SettingController : KabuController
    {
        private ISettingService _settingService;

        public SettingController(ISettingService settingService)
        {
            _settingService = settingService;
        }

        // GET: Setting
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddNew(Setting model)
        {
            if (!ModelState.IsValid)
                return Json(new { IsCompleted = false }, JsonRequestBehavior.AllowGet);

            model.Status = Status.Active;

            _settingService.Create(model);

            return View();
        }

        [HttpGet]
        public ActionResult Settings()
        {
            var model = GenerateTableModel(new TableViewModel<Setting>());

            return PartialView(model);
        }


        private TableViewModel<Setting> GenerateTableModel(TableViewModel<Setting> model)
        {
            var data = _settingService.Get(x => x.Status != Status.Deleted).Result;

            model.Hits =
                data.OrderBy(x => x.Id).Skip((model.CurrentPage - 1) * model.Perpage).Take(model.Perpage).ToList();
            model.TotalCount = data.ToList().Count;
            return model;
        }

        public JsonResult RefreshTableData(TableViewModel<Setting> tableModel)
        {
            var viewResult = RenderRazorViewToString("Settings", GenerateTableModel(tableModel));
            return Json(new { view = viewResult, IsCompleted = true });
        }

        public async Task<JsonResult> Remove(string id)
        {
            var model = await _settingService.FindById(id);

            if (model == null)
                return Json(new { IsCompleted = false, title = "Hata !", message = "Model Bulunamadı !" },
                    JsonRequestBehavior.AllowGet);

            _settingService.Delete(model);

            return Json(new { IsCompleted = true, title = "Başarılı !", message = "Başarı ile silindi !" },
                JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> Load(string id)
        {
            var model = await _settingService.FindById(id);

            if (model == null)
                return Json(new { IsCompleted = false, title = "Hata !", message = "Model Bulunamadı !" },
                    JsonRequestBehavior.AllowGet);

            return Json(new { model, isCompleted = true }, JsonRequestBehavior.AllowGet);
        }


    }
}

KABU_Blog/Blog.AI/Views/Shared/_Alerts.cshtml
@using Blog.Resources
<div class="row-fluid" id="alerts" style="display: none;">
    <div class="box span12">

        <div class="box-header">
            <h2><i class="halflings-icon white white bullhorn"></i><span class="break"></span>@Displays.Alerts</h2>
        </div>
        <div class="box-content alerts">
        </div>

    </div><!--/span-->
</div>

KABU_Blog/Blog.AI/Views/Shared/_Contacts.cshtml
@model Blog.AI.Models.ContactViewModel
<li class="dropdown hidden-phone">
    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="icon-envelope"></i>
        <span class="badge red">
            @Model.UnReadCount
        </span>
    </a>
    <ul class="dropdown-menu messages">
        <li class="dropdown-menu-title">
            <span>@Model.TotalContact adet mesajınız var.</span>
            <a href="#refresh"><i class="icon-repeat"></i></a>
        </li>
        @foreach (var contact in Model.Contacts)
        {
            <li>
                <a href="@Url.Action("ReadMessage", "Contact", new { id = contact.Id })">
                <span class="header">
                <span class="from">
                @contact.Fullname
                </span>
                <span class="time">
                @((DateTime.Now - contact.Created).ToString())
                </span>
                </span>
                <span class="message">
                @contact.Title
                </span>
                </a>
            </li>

        }
        <li>
            <a class="dropdown-menu-sub-footer" href="@Url.Action("Index", "Contact")">Tüm mesajları göster.</a>
        </li>
    </ul>
</li>

KABU_Blog/Blog.AI/Views/Shared/_Header.cshtml
<div class="nav-no-collapse header-nav">
    <ul class="nav pull-right">
        @Html.Action("_Notifications","Common")
        @Html.Action("_LoginPartial", "Profile")
    </ul>
</div>

KABU_Blog/Blog.AI/Views/Shared/_Layout.cshtml
@using Blog.Resources
<!DOCTYPE html>
<html>
<head>

    <!-- start: Meta -->
    <meta charset="utf-8">
    <title>@Displays.AdministratorPanel | @ViewBag.Title</title>
    <meta name="description" content="Bootstrap Metro Dashboard">
    <meta name="author" content="Kağan Kaptan, Aybars Arslan, Burak Koyun, Uğur Demir">
    <!-- end: Meta -->
    <!-- start: Mobile Specific -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- end: Mobile Specific -->
    <!-- start: CSS -->
    <link id="bootstrap-style" href="/Content/bootstrap.min.css" rel="stylesheet">
    <link href="/Content/bootstrap-responsive.min.css" rel="stylesheet">
    <link id="base-style" href="/Content/style.css" rel="stylesheet">
    <link id="base-style-responsive" href="/Content/style-responsive.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&subset=latin,cyrillic-ext,latin-ext' rel='stylesheet' type='text/css'>
    <!-- end: CSS -->
    <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <link id="ie-style" href="/Content/ie.css" rel="stylesheet">
    <![endif]-->
    <!--[if IE 9]>
        <link id="ie9style" href="/Content/ie9.css" rel="stylesheet">
    <![endif]-->
    <!-- start: Favicon -->
    <link rel="shortcut icon" href="/Content/img/favicon.ico">
    <!-- end: Favicon -->

    <script src="/Scripts/jquery-1.9.1.min.js"></script>

</head>

<body>
    <div class="navbar">
        <div class="navbar-inner">
            <div class="container-fluid">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".top-nav.nav-collapse,.sidebar-nav.nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <a class="brand" href="/"><span>KABU Blog</span></a>

                <!-- start: Header Menu -->
                @Html.Action("_Header", "Common")
                <!-- end: Header Menu -->

            </div>
        </div>
    </div>
    <!-- start: Header -->

    <div class="container-fluid-full">
        <div class="row-fluid">

            <!-- start: Main Menu -->
            @Html.Partial("_SideBar")
            <!-- end: Main Menu -->

            <noscript>
                <div class="alert alert-block span10">
                    <h4 class="alert-heading">Warning!</h4>
                    <p>You need to have <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> enabled to use this site.</p>
                </div>
            </noscript>

            <!-- start: Content -->
            <div id="content" class="span10">


                @Html.Action("_Navigation", "Common")
                @Html.Partial("_Alerts")
            @RenderBody()
        </div><!--/.fluid-container-->
        <!-- end: Content -->
    </div><!--/#content.span10-->
</div><!--/fluid-row-->
@*
    Modal
    <div class="modal hide fade" id="myModal">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">×</button>
            <h3>Settings</h3>
        </div>
        <div class="modal-body">
            <p>Here settings can be configured...</p>
        </div>
        <div class="modal-footer">
            <a href="#" class="btn" data-dismiss="modal">Close</a>
            <a href="#" class="btn btn-primary">Save changes</a>
        </div>
    </div>*@

<div class="common-modal modal fade" id="common-Modal1" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-content">
        <ul class="list-inline item-details">
            <li><a href="http://themifycloud.com">Admin templates</a></li>
            <li><a href="http://themescloud.org">Bootstrap themes</a></li>
        </ul>
    </div>
</div>

<div class="clearfix"></div>

<footer>
    <p>
        <span style="text-align:left;float:left">&copy; @DateTime.Now.Year <a href="http://themifycloud.com/downloads/janux-free-responsive-admin-dashboard-template/" alt="Bootstrap_Metro_Dashboard">JANUX Responsive Dashboard</a></span>

    </p>
</footer>

<!-- start: JavaScript-->
<script src="/Scripts/jquery-migrate-1.0.0.min.js"></script>

<script src="/Scripts/jquery-ui-1.10.0.custom.min.js"></script>

<script src="/Scripts/jquery.ui.touch-punch.js"></script>

<script src="/Scripts/modernizr.js"></script>

<script src="/Scripts/bootstrap.min.js"></script>

<script src="/Scripts/jquery.cookie.js"></script>

<script src='/Scripts/fullcalendar.min.js'></script>

<script src='/Scripts/jquery.dataTables.min.js'></script>
<script src="/Scripts/excanvas.js"></script>
<script src="/Scripts/jquery.flot.js"></script>
<script src="/Scripts/jquery.flot.pie.js"></script>
<script src="/Scripts/jquery.flot.stack.js"></script>
<script src="/Scripts/jquery.flot.resize.min.js"></script>

<script src="/Scripts/jquery.chosen.min.js"></script>

<script src="/Scripts/jquery.uniform.min.js"></script>

<script src="/Scripts/jquery.cleditor.min.js"></script>

<script src="/Scripts/jquery.noty.js"></script>

<script src="/Scripts/jquery.elfinder.min.js"></script>

<script src="/Scripts/jquery.raty.min.js"></script>

<script src="/Scripts/jquery.iphone.toggle.js"></script>

<script src="/Scripts/jquery.uploadify-3.1.min.js"></script>

<script src="/Scripts/jquery.gritter.min.js"></script>

<script src="/Scripts/jquery.imagesloaded.js"></script>

<script src="/Scripts/jquery.masonry.min.js"></script>

<script src="/Scripts/jquery.knob.modified.js"></script>

<script src="/Scripts/jquery.sparkline.min.js"></script>

<script src="/Scripts/counter.js"></script>

<script src="/Scripts/retina.js"></script>
<script src="/Scripts/custom.js"></script>
<script src="/Scripts/functions.js"></script>
<!-- end: JavaScript-->

@Scripts.Render("~/bundles/jqueryval")
@RenderSection("scripts", required: false)
</body>
</html>

KABU_Blog/Blog.AI/Views/Shared/_Navigation.cshtml
@using Blog.Resources
@model dynamic

<ul class="breadcrumb">
    <li>
        <i class="icon-home"></i>
        <a href="/">@Displays.MainPage</a>
        <i class="icon-angle-right"></i>
    </li>
    <li><a href="/@Model.controller">@Model.controller</a>
        <i class="icon-angle-right"></i></li>
    <li>
        <a href="/@Model.controller/@Model.action">@Model.action</a>
    </li>
</ul>

KABU_Blog/Blog.AI/Views/Shared/_Notifications.cshtml
<li class="dropdown hidden-phone">
    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="icon-bell"></i>
        <span class="badge red">
            7
        </span>
    </a>
    <ul class="dropdown-menu notifications">
        <li class="dropdown-menu-title">
            <span>You have 11 notifications</span>
            <a href="#refresh"><i class="icon-repeat"></i></a>
        </li>
        <li>
            <a href="#">
                <span class="icon blue"><i class="icon-user"></i></span>
                <span class="message">New user registration</span>
                <span class="time">1 min</span>
            </a>
        </li>
        <li>
            <a href="#">
                <span class="icon green"><i class="icon-comment-alt"></i></span>
                <span class="message">New comment</span>
                <span class="time">7 min</span>
            </a>
        </li>
        <li>
            <a href="#">
                <span class="icon green"><i class="icon-comment-alt"></i></span>
                <span class="message">New comment</span>
                <span class="time">8 min</span>
            </a>
        </li>
        <li>
            <a href="#">
                <span class="icon green"><i class="icon-comment-alt"></i></span>
                <span class="message">New comment</span>
                <span class="time">16 min</span>
            </a>
        </li>
        <li>
            <a href="#">
                <span class="icon blue"><i class="icon-user"></i></span>
                <span class="message">New user registration</span>
                <span class="time">36 min</span>
            </a>
        </li>
        <li>
            <a href="#">
                <span class="icon yellow"><i class="icon-shopping-cart"></i></span>
                <span class="message">2 items sold</span>
                <span class="time">1 hour</span>
            </a>
        </li>
        <li class="warning">
            <a href="#">
                <span class="icon red"><i class="icon-user"></i></span>
                <span class="message">User deleted account</span>
                <span class="time">2 hour</span>
            </a>
        </li>
        <li class="warning">
            <a href="#">
                <span class="icon red"><i class="icon-shopping-cart"></i></span>
                <span class="message">New comment</span>
                <span class="time">6 hour</span>
            </a>
        </li>
        <li>
            <a href="#">
                <span class="icon green"><i class="icon-comment-alt"></i></span>
                <span class="message">New comment</span>
                <span class="time">yesterday</span>
            </a>
        </li>
        <li>
            <a href="#">
                <span class="icon blue"><i class="icon-user"></i></span>
                <span class="message">New user registration</span>
                <span class="time">yesterday</span>
            </a>
        </li>
        <li class="dropdown-menu-sub-footer">
            <a>View all notifications</a>
        </li>
    </ul>
</li>
<!-- start: Notifications Dropdown -->
@*<li class="dropdown hidden-phone">
    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="icon-calendar"></i>
        <span class="badge red">
            5
        </span>
    </a>
    <ul class="dropdown-menu tasks">
        <li class="dropdown-menu-title">
            <span>You have 17 tasks in progress</span>
            <a href="#refresh"><i class="icon-repeat"></i></a>
        </li>
        <li>
            <a href="#">
                <span class="header">
                    <span class="title">iOS Development</span>
                    <span class="percent"></span>
                </span>
                <div class="taskProgress progressSlim red">80</div>
            </a>
        </li>
        <li>
            <a href="#">
                <span class="header">
                    <span class="title">Android Development</span>
                    <span class="percent"></span>
                </span>
                <div class="taskProgress progressSlim green">47</div>
            </a>
        </li>
        <li>
            <a href="#">
                <span class="header">
                    <span class="title">ARM Development</span>
                    <span class="percent"></span>
                </span>
                <div class="taskProgress progressSlim yellow">32</div>
            </a>
        </li>
        <li>
            <a href="#">
                <span class="header">
                    <span class="title">ARM Development</span>
                    <span class="percent"></span>
                </span>
                <div class="taskProgress progressSlim greenLight">63</div>
            </a>
        </li>
        <li>
            <a href="#">
                <span class="header">
                    <span class="title">ARM Development</span>
                    <span class="percent"></span>
                </span>
                <div class="taskProgress progressSlim orange">80</div>
            </a>
        </li>
        <li>
            <a class="dropdown-menu-sub-footer">View all tasks</a>
        </li>
    </ul>
</li>*@
<!-- end: Notifications Dropdown -->
<!-- start: Message Dropdown -->

@Html.Action("_Contacts","Common")

KABU_Blog/Blog.AI/Views/Shared/_SideBar.cshtml
<div id="sidebar-left" class="span2">
    <div class="nav-collapse sidebar-nav">
        <ul class="nav nav-tabs nav-stacked main-menu">
            <li><a href="@Url.Action("Index","Dashboard")"><i class="icon-bar-chart"></i><span class="hidden-tablet"> Dashboard</span></a></li>
            <li>
            <li><a href="@Url.Action("Index","Contact")"><i class="icon-bar-chart"></i><span class="hidden-tablet"> Contact</span></a></li>
            <li>
            <li>
                <a class="dropmenu" href="#"><i class="icon-folder-close-alt"></i><span class="hidden-tablet"> Kategoriler</span></a>
                <ul>
                    <li><a class="submenu" href="@Url.Action("Index", "Category")"><i class="icon-file-alt"></i><span class="hidden-tablet"> Kategori</span></a></li>
                    <li><a class="submenu" href="@Url.Action("New", "Category")"><i class="icon-file-alt"></i><span class="hidden-tablet"> Yeni Kategori</span></a></li>
                </ul>
            </li>
            <li>
                <a class="dropmenu" href="#"><i class="icon-folder-close-alt"></i><span class="hidden-tablet"> Yazılar</span></a>
                <ul>
                    <li><a class="submenu" href="@Url.Action("Index","Article")"><i class="icon-file-alt"></i><span class="hidden-tablet"> Yazı</span></a></li>
                    <li><a class="submenu" href="@Url.Action("New","Article")"><i class="icon-file-alt"></i><span class="hidden-tablet"> Yeni Yazı</span></a></li>
                </ul>
            </li>
            <li><a href="@Url.Action("Index","Blocker")"><i class="icon-bar-chart"></i><span class="hidden-tablet"> Yasaklanmış Kullanıcılar</span></a></li>
            <li>
            <li><a href="@Url.Action("Index","Setting")"><i class="icon-bar-chart"></i><span class="hidden-tablet"> Ayarlar</span></a></li>
            <li>
        </ul>
    </div>
</div>